# Nixkell config

ghc = "8.10.4"

[env]
tools = [
  "cabal-install",
  "haskell-language-server",
  "haskellPackages.aeson",
  "haskellPackages.containers",
  "haskellPackages.exceptions",
  "haskellPackages.http-api-data",
  "haskellPackages.http-client",
  "haskellPackages.http-client-tls",
  "haskellPackages.http-types",
  "haskellPackages.mtl",
  "haskellPackages.network-uri",
  "haskellPackages.servant",
  "haskellPackages.servant-client",
  "haskellPackages.servant-client-core",
  "haskellPackages.servant-server",
  "haskellPackages.swagger2",
  "haskellPackages.text",
  "haskellPackages.time",
  "haskellPackages.transformers",
  "haskellPackages.uuid",
  "haskellPackages.wai",
  "haskellPackages.warp",
  "hlint",
  "niv",
  "nixpkgs-fmt",
  "ormolu"
]

[ignore]
files = [
  "README.md",
]
paths = [
  ".github",
  ".vscode",
]
